# Even Fibonacci numbers
# https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fibonacci_up_to(below):
    fibonacci = [0, 1]
    n = 1

    while fibonacci[n] < below:
        fibonacci.append(fibonacci[n] + fibonacci[n-1])
        n += 1

    return fibonacci[:-1]


def sum_of_even_fibonaccis(below):
    fibonaccis = fibonacci_up_to(below)
    even_fibonaccis = [fib for fib in fibonaccis if fib % 2 == 0]
    return sum(even_fibonaccis)
